### ISSUE TITLE
Getting  error

### ISSUE THREAD

**Issue by PritishPandey** [Prakashvanapalli/CAX_Mobile_Theme_Classification#1]
Hi Prakash, 
I am new to neural nets and python.
While trying to run your model, i am getting error while running this cell
```
model_final.fit_generator(
train_generator,
samples_per_epoch = nb_train_samples,
epochs = epochs,
validation_data = validation_generator,
nb_val_samples = nb_validation_samples,
callbacks = [ModelCheckpoint("model_resnet_50_iteration_1.h5")])
```
Getting this error
**fit_generator() got an unexpected keyword argument 'epochs'**

_I am working on Python 3.5/Keras 1.2.2 and Jupyter Notebook on Ubuntu 16.04_

TIA

**Comment by Prakashvanapalli** [comment]
Hi,

Give number of epochs before you run the cell. Like

epochs = 50

**Comment by PritishPandey** [comment]
that i ran... i ran your code cell by cell and when i reached this part, i
got that error.

**Comment by Prakashvanapalli** [comment]
its running for me. try to upgrade your keras package and check.

    fit_generator(self, generator, steps_per_epoch, epochs=1, verbose=1, callbacks=None, validation_data=None, validation_steps=None, class_weight=None, max_q_size=10, workers=1, pickle_safe=False, initial_epoch=0)

**Comment by PritishPandey** [comment]
hey Prakash..Updating Keras worked. Thanks a lot.But it is too slow in my
pc.
I have a laptop with i5 with 8gb ram.
I do have a graphics card in my laptop.. NVIDIA GEFORCE 940M.. I tried
installing CUDA 8 with drivers but somehow messed up the GUI.
Can you help me with some link to install it properly so that i can make
use of the gpu. Which CUDA version i should use?

Also is there any link to understand simple CNN models for
misclassification problems.like a simple CNN model for this problem.
I m sorry, i am asking too many questions.. may be too excited and curious.
:) Please do reply when you have free time.

Thanks a lot. :)

**Comment by pratos** [comment]
@PritishPandey this is @Prakashvanapalli 's colleague.

We had attempted to get GPU setup on our machine a few months back, we did it successfully. Getting GPU Setup for Deep Learning is a very tedious process and unfortunately we haven't documented it properly. Still fragmented over a lot of blogposts, as soon as we get bandwidth to prepare a nice blogpost we would let you know.

For now I can point you towards a few articles, but sadly things are at changing at such a breath neck speed there's a possibility that it won't work for your case. 

Here are the few articles that we referred to:
(_Note: Our's is an Ubuntu16.04 system, included a Windows setup as well_)

* Follow this guide, more or less a similar pattern we followed (http://deeplearning.lipingyang.org/2017/01/18/install-gpu-tensorflow-ubuntu-16-04/)

Other sources:
1. [floydhub/dl-setup](https://github.com/floydhub/dl-setup)
2. [Setup for 16.04](http://www.computervisionbytecnalia.com/en/2016/06/deep-learning-development-setup-for-ubuntu-16-04-xenial/)
3. [How to solve the graphics issues caused by X11](https://askubuntu.com/questions/760934/graphics-issues-after-while-installing-ubuntu-16-04-16-10-with-nvidia-graphics)
4. [Installing GPU Tensorflow in Xenial16.04](https://alliseesolutions.wordpress.com/2016/09/08/install-gpu-tensorflow-from-sources-w-ubuntu-16-04-and-cuda-8-0-rc/)
5. [Older setup](http://kislayabhi.github.io/Installing_CUDA_with_Ubuntu/)
6. [Deep Learning Installation](https://www.born2data.com/2016/deeplearning_install-part1.html)
7. [NVIDIA Setup]()
8. [Deep Learning setup for Windows](https://github.com/philferriere/dlwin)

Hope this could be of some help. If you are using Ubuntu, there's a good chance that you'll break your head on installing NVIDIA Drivers. I did, so read the below blogs/stackoverflow answers to navigate:
1. [NVIDIA Driver issues](http://technozed.com/fix-nvidia-graphical-issues-installing-ubuntu-16-04/)
2. [How to chose the driver for Linux](https://linuxconfig.org/how-to-install-the-latest-nvidia-drivers-on-ubuntu-16-04-xenial-xerus).

Regards, Prathamesh

**Comment by PritishPandey** [comment]
Thanks prakash for all the help. I will try installing on separate OS...One
more thing.. we have train data with 16 folders  with images and test has
only images (mixed, no folders)
How come you are getting 466 images from test, while i am getting 0 (Found
0 images belonging to 0 classes.)

train_generator = train_datagen.flow_from_directory(

    train_data_dir,

    target_size=(img_width, img_height),

    batch_size=batch_size,

    class_mode='categorical')

​

validation_generator = test_datagen.flow_from_directory(

    validation_data_dir,

    target_size=(img_width, img_height),

    batch_size=batch_size,

    class_mode='categorical')

*Found 4590 images belonging to 16 classes.
Found 0 images belonging to 0 classes.
*

**Comment by PritishPandey** [comment]
i meant you have taken taken 466 samples manually from train for validation
and put in different folder test?

**Comment by Prakashvanapalli** [comment]
I have split my data into train and test. [link_here](https://github.com/Prakashvanapalli/CAX_Mobile_Theme_Classification/blob/master/train_test_split.ipynb)

There are a lot of things missing here and there. Will try to update it soon. closing this issue for now.

**Comment by PritishPandey** [comment]
yes sure... thanks a lot prakash for all the help.. :)

On Apr 14, 2017 6:19 PM, "PrakashR" <notifications@github.com> wrote:

I have split my data into train and test. link_here
<https://github.com/Prakashvanapalli/CAX_Mobile_Theme_Classification/blob/master/train_test_split.ipynb>

There are a lot of things missing here and there. Will try to update it
soon. closing this issue for now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Prakashvanapalli/CAX_Mobile_Theme_Classification/issues/1#issuecomment-294148225>,
or mute the thread
